name: Dockerfile Push

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron:  '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - 
      name: Checkout ðŸ›Ž memory
      uses: actions/checkout@v3

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push Dockerfile
      run: |
        docker build . --file docker/Dockerfile --tag unifyai/memory:latest
        docker push unifyai/memory:latest
