name: nightly-tests
on: [push]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy Memory
        uses: actions/checkout@v2
        with:
          path: memory
          persist-credentials: false

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/memory:/memory unifyai/ivy-memory:latest python3 -m pytest ivy_memory_tests/
