name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸Ivy Memory
        uses: actions/checkout@v2
        with:
          path: memory
          persist-credentials: false

      - name: Run Tests
        run: |
          cd memory
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          docker run --rm -v `pwd`:/memory unifyai/memory:latest python3 -m pytest ivy_memory_tests/
